### PR TITLE
DM-14728: Add asEigenArray/Matrix returning Eigen::Map

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Review by TallJimbo — CHANGES_REQUESTED** [review]
Ah, this reminds me why I had done the pybind11 suffix fix via a patch here: I assumed LSST was probably the only consumer of ndarray that couldn't just upgrade to pybind11 2.2.x to fix this problem, and hence the only consumer that would want this rather unportable, hacky fix.  I think that's probably the right reasoning, so I think I may do a quick revert of that commit in ndarray, add a note to the README about pybind11 versions, push out 1.5.1, and then have you restore this patch.

**Comment by TallJimbo** [comment]
ndarray 1.5.1 is out, without the pybind11 2.1.x suffix fix.

**Comment by r-owen** [comment]
Can you update the CHANGELOG to say SWIG support is removed as well?

**Comment by TallJimbo** [comment]
> Can you update the CHANGELOG to say SWIG support is removed as well?

Already done.

**Comment by r-owen** [comment]
I have updated to 1.5.1 and restored the patch. It builds on my Mac and I'm about to start another Jenkins run. Please have another look.

For future reference: please consider removing the .gitignore file when making the tarball; due to a bug in lsstsw rebuild it ends up replacing the original.

**Review by TallJimbo — APPROVED** [review]

**Comment by TallJimbo** [comment]
> For future reference: please consider removing the .gitignore file when making the tarball; due to a bug in lsstsw rebuild it ends up replacing the original.

I just use GitHub's "draft new release" to make tarballs, which is way easier than doing them manually.

**Pull request merged**
